[project]
name = "alphabet-sort"
version = "0.1.8"
tags = ["sorting", "names", "multi-turn", "xml", "synthetic", "tools"]
license = "Apache-2.0"
description = "This task requires the model to maintain and update an alphabetically sorted list of names across multiple conversation turns."
dependencies = [
    "verifiers>=0.1.3",
    "datasets>=2.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["alphabet_sort.py"]