endpoints_path = "../endpoints.toml"

model = "openai/gpt-4.1-mini"
num_examples = 50
rollouts_per_example = 3
save_results = true

[[eval]]
env_id = "alphabet-sort"

[eval.env_args]
min_turns = 3
max_turns = 5
power_per_turn = false
