MODEL_NO_RESPONSE_TIMEOUT_SECONDS = 21_600
SANDBOX_CREATE_TIMEOUT_SECONDS = 3_600
SANDBOX_READY_TIMEOUT_SECONDS = 3_600
SANDBOX_SETUP_STEP_TIMEOUT_SECONDS = 900
FILE_TRANSFER_TIMEOUT_SECONDS = 900
BACKGROUND_JOB_POLL_INTERVAL_SECONDS = 3
SANDBOX_LEASE_TTL_MINUTES = 24 * 60
TEST_PHASE_TIMEOUT_SECONDS: int | None = None
OPENENV_STARTUP_TIMEOUT_SECONDS = 300
OPENENV_STARTUP_POLL_INTERVAL_SECONDS = 1.0
OPENENV_HEALTH_REQUEST_TIMEOUT_SECONDS = 10.0
OPENENV_SCHEMA_REQUEST_TIMEOUT_SECONDS = 30.0
OPENENV_WAIT_FOR_CREATION_ATTEMPTS = 120


def test_phase_timeout_seconds(value: object | None) -> int | None:
    if value is None:
        return TEST_PHASE_TIMEOUT_SECONDS
    if isinstance(value, bool) or not isinstance(value, int | float | str):
        raise TypeError("Test phase timeout must be numeric seconds.")
    return int(float(value))
