model = "Qwen/Qwen2.5-0.5B-Instruct"

[env]
id = "primeintellect/alphabet-sort"

[inference]
gpus = 6

[inference.args]
enforce_eager = true

[trainer]
gpus = 2

[trainer.args]
run_name = "alphabet-sort"
micro_batch_size = 32
rollouts_per_example = 16
batch_size = 512
max_steps = 200
max_seq_len = 512
