model = "Qwen/Qwen3-4B-Instruct-2507"

[env]
id = "primeintellect/alphabet-sort"

[env.args]
min_turns = 2
max_turns = 2

[inference]
gpus = 1

[inference.args]
enforce_eager = true

[trainer]
gpus = 1

[trainer.args]
run_name = "alphabet-sort"
micro_batch_size = 16
rollouts_per_example = 16
batch_size = 512
max_steps = 100
max_seq_len = 2048
max_tokens = 512
importance_sampling_level = "token"