model = "Qwen/Qwen3-4B-Instruct-2507"

[env]
id = "alphabet-sort"

[env.args]
min_turns = 3
max_turns = 3
min_names_per_turn = 1
max_names_per_turn = 4
similarity_power = 8
power_per_turn = false

[inference]
gpus = 1

[inference.args]
enforce_eager = true

[trainer]
gpus = 1

[trainer.args]
run_name = "alphabet-sort"
lora_rank = 32
lora_alpha = 64
micro_batch_size = 4
rollouts_per_example = 8
batch_size = 512
max_steps = 100
max_seq_len = 2048
max_tokens = 768