model = "Qwen/Qwen2.5-1.5B-Instruct"

[env]
id = "primeintellect/sentence-repeater"

[inference]
gpus = 6

[inference.args]
enforce_eager = true

[trainer]
gpus = 6

[trainer.args]
run_name = "sentence-repeater"
micro_batch_size = 8
rollouts_per_example = 16
batch_size = 512
max_steps = 200
max_seq_len = 4096
