model = "Qwen/Qwen3-4B-Instruct-2507"

[env]
id = "will/wordle"

[env.args]
use_think = true

[inference]
gpus = 1

[inference.args]
enforce_eager = true

[trainer]
gpus = 1

[trainer.args]
run_name = "wordle"
micro_batch_size = 2
rollouts_per_example = 16
batch_size = 512
max_steps = 500
max_tokens = 1024
max_seq_len = 4096
