# This config demonstrates per-environment parameter customization

# List of environments to evaluate
environment_ids = ["gsm8k"]

# Global defaults (applied to all environments unless overridden)
num_examples = 10
rollouts_per_example = 3
max_concurrent = 32

# Model configuration
[model]
name = "gpt-4o-mini"

# Global sampling parameters
[sampling]
temperature = 0.7
max_tokens = 2048

# Per-environment configuration
[env.gsm8k]
num_examples = 20
rollouts_per_example = 2
max_concurrent = 16

max_tokens = 512
use_think = true
num_eval_examples = 20

# API configuration (optional)
api_key_var = "OPENAI_API_KEY"
api_base_url = "https://api.openai.com/v1"

