[project]
name = "terminalbench"
version = "0.1.0"
dependencies = [
    "verifiers>=0.1.0",
    "docker>=6.0.0",
    "datasets>=2.14.0",
    "PyYAML>=6.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["terminalbench.py"] 