"""Task data, configuration, behavior, and scoring.

`TaskData` is the wire half: a frozen pydantic model carrying everything a rollout's
row IS — the base fields plus your typed, task-specific fields. It rides on
`trace.task.data`, is what `traces.jsonl` stores, and what tool servers receive
over the `/task` channel. Subclass it per dataset.

`Task` is the behavior half: runtime prep (`setup`/`finalize`), server declarations
(`tools`), well-formedness (`validate`), and per-trace judgement
(`@reward`/`@metric` methods plus the plugged judges from `config.judges`, run by
`score`). Subclass per dataset and parameterize `Task[MyData, MyState, MyConfig]`
(all three default); judgement that compares sibling traces lives on
`Env.finalize` instead.

A Task instance is shared across its rollouts (`-r n` runs hold the same instance),
so hooks must not stash per-rollout state on `self` — that lives on the trace
(`trace.state`).

On the wire only the data travels (plus the producing class's name,
`trace.task.type`): a saved row reads back as `WireTaskData` without importing the
taskset; a re-scoring consumer (`replay`) rebuilds the declared `TaskData` type and
wraps it in the declared `Task` — one task type per taskset.
"""

from __future__ import annotations

import copy
import inspect
import logging
from collections.abc import Mapping
from typing import TYPE_CHECKING, ClassVar, Generic, Self

from pydantic import BaseModel, ConfigDict, Field
from pydantic_config import BaseConfig
from typing_extensions import TypeVar

from verifiers.v1.artifacts import Artifact
from verifiers.v1.configs.task import TaskConfig
from verifiers.v1.decorators import discover_decorated, invoke_all
from verifiers.v1.errors import TaskError, boundary
from verifiers.v1.state import StateT
from verifiers.v1.types import Messages, content_text
from verifiers.v1.utils.generic import concrete_type

if TYPE_CHECKING:
    from verifiers.v1.judge import Judge
    from verifiers.v1.mcp import Toolset
    from verifiers.v1.runtimes import Runtime
    from verifiers.v1.trace import Trace

logger = logging.getLogger(__name__)


class TaskResources(BaseModel):
    """Optional resource limits for the task."""

    model_config = ConfigDict(frozen=True)

    cpu: float | None = None
    """CPU cores."""
    memory: float | None = None
    """Memory in GB."""
    gpu: str | None = None
    """GPU spec, e.g. "A100" or "A100:2" (type[:count])."""
    disk: float | None = None
    """Disk in GB (enforced by prime; advisory on docker/modal)."""


class TaskTimeout(BaseModel):
    """Optional per-task timeout overrides, in seconds."""

    model_config = ConfigDict(frozen=True)

    setup: float | None = None
    """Timeout (in seconds) for the task's setup hook."""
    agent: float | None = None
    """Timeout (in seconds) for the agent's solve attempt."""
    finalize: float | None = None
    """Timeout (in seconds) for the task's finalize hook."""
    scoring: float | None = None
    """Timeout (in seconds) for the task's scoring."""


class TaskData(BaseModel):
    model_config = ConfigDict(frozen=True)

    idx: int | None = None
    """Taskset-autogenerated index."""
    name: str | None = None
    """Optional human-readable task name."""
    description: str | None = None
    """Optional human-readable task description."""

    prompt: str | Messages | None = None
    """Initial user prompt; unset if the user opens the conversation."""
    system_prompt: str | None = None
    """Optional system prompt to prepend to the user prompt."""

    image: str | None = None
    """Optional Docker image to use for the task. Only relevant for tasks that run in a container."""
    workdir: str | None = None
    """Optional working directory to use for the task. Only relevant for tasks that run in a container."""

    network_allow: list[str] = Field(default_factory=lambda: ["*"])
    """Execution-time destinations requested by this task. `*` leaves the runtime
    allowlist unchanged; a concrete list replaces a wildcard or combines with existing
    entries. Prime runtimes accept host-level entries and require `vm=true`."""
    network_block: list[str] = Field(default_factory=list)
    """Execution-time destinations denied by this task and combined with runtime
    blocks. Non-empty concrete allowlists cannot be combined with blocklists. Docker
    framework routes take precedence; ordinary Prime deny rules pass through unchanged."""

    artifacts: list[Artifact] = Field(default_factory=list)
    """Paths collected from one runtime and restored at the same locations in another,
    on top of the implicitly collected `/logs/artifacts/` convention dir. Declare
    runtime outputs that must cross that boundary. A declared path that is missing at
    collection time fails the rollout."""

    timeout: TaskTimeout = TaskTimeout()
    resources: TaskResources = TaskResources()

    @property
    def prompt_text(self) -> str:
        if isinstance(self.prompt, str):
            return self.prompt
        texts = [content_text(message.content) for message in self.prompt or []]
        return "\n\n".join(text for text in texts if text)


class WireTaskData(TaskData):
    """Wire form that preserves task-specific fields without importing the task class."""

    model_config = ConfigDict(extra="allow")


DataT = TypeVar("DataT", bound=TaskData)
ConfigT = TypeVar("ConfigT", bound=TaskConfig, default=TaskConfig)


def task_data_cls(cls: type) -> type[TaskData]:
    """Resolve a task's `TaskData` specialization through its MRO, else `TaskData`."""
    return concrete_type(cls, TaskData) or TaskData


def task_config_cls(cls: type) -> type[TaskConfig]:
    """Resolve a task's `TaskConfig` specialization through its MRO, else `TaskConfig`."""
    return concrete_type(cls, TaskConfig) or TaskConfig


def resolve_server_config(
    owner: str, config: BaseConfig, server_cls: type, *, sole: bool = True
) -> BaseConfig:
    """The config a declared server class is built with, resolved off `config`'s
    fields: exact type match, else — only for a `sole` declared server — the unique
    isinstance match, else a default-constructed one. Two matching fields raise; the
    `server_config` methods are the explicit-pairing override. The isinstance
    fallback is `sole`-gated because with several servers a subclass-typed field
    could silently pair with the wrong one."""
    cfg_cls = server_cls._config_cls()
    values = {name: getattr(config, name) for name in type(config).model_fields}
    matched = [name for name, v in values.items() if type(v) is cfg_cls]
    if not matched and sole:
        matched = [name for name, v in values.items() if isinstance(v, cfg_cls)]
    if len(matched) > 1:
        raise TaskError(
            f"{owner}: ambiguous config for {server_cls.__name__} — config fields "
            f"{matched} all match {cfg_cls.__name__}; override `server_config` to pair "
            f"them explicitly"
        )
    if matched:
        return values[matched[0]]
    return cfg_cls()


class Task(Generic[DataT, StateT, ConfigT]):
    NEEDS_CONTAINER: ClassVar[bool] = False
    """Whether the task needs a containerized environment (isolated filesystem, etc.)."""

    tools: ClassVar[tuple[type[Toolset], ...]] = ()

    def __init__(self, data: DataT, config: ConfigT | None = None) -> None:
        self.data = data
        self.config = config if config is not None else task_config_cls(type(self))()

    def with_system_prompt(self, system_prompt: str) -> Self:
        """A shallow copy of this task with `data.system_prompt` overridden. Copies the
        instance instead of reconstructing via `type(self)(...)`, so a subclass with a
        non-`(data, config)` constructor or extra load-time state keeps it. Used to apply the
        config-layer / GEPA system prompt (see `TasksetConfig` and `verifiers.v1.gepa`)."""
        clone = copy.copy(self)
        clone.data = self.data.model_copy(update={"system_prompt": system_prompt})
        return clone

    def plugged_judges(self) -> list[Judge]:
        from verifiers.v1.loaders import load_judge

        return [load_judge(config) for config in self.config.judges]

    def server_config(self, server_cls: type) -> BaseConfig:
        """The config a declared server class (`tools`) is built with (see
        `resolve_server_config`). Override to pair explicitly."""
        return resolve_server_config(
            type(self).__name__,
            self.config,
            server_cls,
            sole=len(set(type(self).tools)) == 1,
        )

    def tool_servers(self) -> list[Toolset]:
        return [cls(self.server_config(cls)) for cls in type(self).tools]

    async def setup(self, trace: Trace, runtime: Runtime) -> None:
        return None

    async def finalize(self, trace: Trace, runtime: Runtime) -> None:
        return None

    async def validate(self, runtime: Runtime) -> bool:
        return True

    async def score(
        self,
        trace: Trace,
        runtime: Runtime | None = None,
    ) -> None:
        def requires_runtime(fn) -> bool:
            param = inspect.signature(fn).parameters.get("runtime")
            # A defaulted runtime parameter can still be called offline with None.
            return param is not None and param.default is inspect.Parameter.empty

        judges = self.plugged_judges()
        available = {"task": self.data, "trace": trace}
        if runtime is not None:
            available["runtime"] = runtime

        async with boundary(TaskError, f"task {type(self).__name__} scoring"):
            metrics = discover_decorated(self, "metric")
            rewards = discover_decorated(self, "reward")
            if runtime is None:
                skipped = [
                    fn.__name__ for fn in (*metrics, *rewards) if requires_runtime(fn)
                ] + [
                    judge.reward_name
                    for judge in judges
                    if requires_runtime(judge.score)
                ]
                if skipped:
                    logger.info(
                        "score: no runtime — skipped runtime-dependent signals: %s",
                        skipped,
                    )
                metrics = [fn for fn in metrics if not requires_runtime(fn)]
                rewards = [fn for fn in rewards if not requires_runtime(fn)]
                judges = [
                    judge for judge in judges if not requires_runtime(judge.score)
                ]

            metric_results = await invoke_all(metrics, available)
            for fn, result in zip(metrics, metric_results):
                if isinstance(result, Mapping):
                    trace.record_metrics(result)
                else:
                    trace.record_metric(fn.__name__, result)
            reward_results = await invoke_all(rewards, available)
            for fn, result in zip(rewards, reward_results):
                weight = getattr(fn, "_vf_weight", 1.0)
                items = (
                    result.items()
                    if isinstance(result, Mapping)
                    else [(fn.__name__, result)]
                )
                for key, value in items:
                    trace.record_reward(key, value, weight)
            judge_results = await invoke_all(
                [judge.score for judge in judges], available
            )
            for judge, result in zip(judges, judge_results):
                items = (
                    result.items()
                    if isinstance(result, Mapping)
                    else [(judge.reward_name, result)]
                )
                for key, value in items:
                    trace.record_reward(key, value, judge.config.weight)


TaskT = TypeVar("TaskT", bound=Task)
