from verifiers.envs.experimental.sandbox_mixin import SandboxMixin

__all__ = [
    "Binding",
    "BindingContext",
    "Channel",
    "ChannelConfig",
    "ChannelContext",
    "ChannelMap",
    "CliConfig",
    "CliMetrics",
    "CliPaths",
    "DatasetTaskset",
    "EndpointConfig",
    "Env",
    "HarborRubric",
    "HarborTaskset",
    "Harness",
    "Resources",
    "RunConfig",
    "SandboxConfig",
    "SandboxMixin",
    "SandboxBashTool",
    "SandboxEditTool",
    "SandboxPythonTool",
    "SandboxRuntime",
    "SandboxScoring",
    "SandboxSeed",
    "SandboxSetup",
    "SandboxSpec",
    "SandboxTimeouts",
    "SandboxTool",
    "Taskset",
    "SandboxTaskSet",
    "Task",
    "TaskSet",
    "CallableTool",
    "MCPTool",
    "ResourceBinding",
    "Toolset",
    "StateBinding",
    "TaskBinding",
    "User",
    "ComposableEnv",
]


def __getattr__(name: str):
    _lazy = {
        "Binding": "verifiers.envs.experimental.binding:Binding",
        "BindingContext": "verifiers.envs.experimental.binding:BindingContext",
        "Channel": "verifiers.envs.experimental.channels:Channel",
        "ChannelConfig": "verifiers.envs.experimental.channels:ChannelConfig",
        "ChannelContext": "verifiers.envs.experimental.channels:ChannelContext",
        "ChannelMap": "verifiers.envs.experimental.channels:ChannelMap",
        "CliConfig": "verifiers.envs.experimental.configs:CliConfig",
        "CliMetrics": "verifiers.envs.experimental.configs:CliMetrics",
        "CliPaths": "verifiers.envs.experimental.configs:CliPaths",
        "DatasetTaskset": "verifiers.envs.experimental.modules.tasksets:DatasetTaskset",
        "EndpointConfig": "verifiers.envs.experimental.configs:EndpointConfig",
        "Env": "verifiers.envs.experimental.env:Env",
        "HarborRubric": "verifiers.envs.experimental.modules.tasksets:HarborRubric",
        "HarborTaskset": "verifiers.envs.experimental.modules.tasksets:HarborTaskset",
        "Harness": "verifiers.envs.experimental.harness:Harness",
        "Resources": "verifiers.envs.experimental.resources:Resources",
        "RunConfig": "verifiers.envs.experimental.configs:RunConfig",
        "SandboxConfig": "verifiers.envs.experimental.configs:SandboxConfig",
        "SandboxBashTool": "verifiers.envs.experimental.modules.tools:SandboxBashTool",
        "SandboxEditTool": "verifiers.envs.experimental.modules.tools:SandboxEditTool",
        "SandboxPythonTool": "verifiers.envs.experimental.modules.tools:SandboxPythonTool",
        "SandboxRuntime": "verifiers.envs.experimental.configs:SandboxRuntime",
        "SandboxScoring": "verifiers.envs.experimental.configs:SandboxScoring",
        "SandboxSeed": "verifiers.envs.experimental.channels:SandboxSeed",
        "SandboxSetup": "verifiers.envs.experimental.configs:SandboxSetup",
        "SandboxTimeouts": "verifiers.envs.experimental.channels:SandboxTimeouts",
        "SandboxTool": "verifiers.envs.experimental.modules.tools:SandboxTool",
        "Taskset": "verifiers.envs.experimental.taskset:Taskset",
        "Toolset": "verifiers.envs.experimental.toolset:Toolset",
        "User": "verifiers.envs.experimental.channels:User",
        "SandboxSpec": "verifiers.envs.experimental.channels:SandboxSpec",
        "SandboxTaskSet": "verifiers.envs.experimental.composable:SandboxTaskSet",
        "Task": "verifiers.envs.experimental.task:Task",
        "TaskSet": "verifiers.envs.experimental.composable:TaskSet",
        "CallableTool": "verifiers.envs.experimental.toolset:CallableTool",
        "MCPTool": "verifiers.envs.experimental.toolset:MCPTool",
        "ResourceBinding": "verifiers.envs.experimental.binding:ResourceBinding",
        "StateBinding": "verifiers.envs.experimental.binding:StateBinding",
        "TaskBinding": "verifiers.envs.experimental.binding:TaskBinding",
        "ComposableEnv": "verifiers.envs.experimental.composable:ComposableEnv",
    }
    if name in _lazy:
        import importlib

        module_path, attr = _lazy[name].split(":")
        return getattr(importlib.import_module(module_path), attr)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
